### ISSUE TITLE
RSA Encryption

### ISSUE THREAD

**Issue by SKocur** [SKocur/Image-Cipher#2]
Implement valid RSA Encryption in [RSAEncryption.java](https://github.com/SKocur/Image-Cipher/blob/master/src/java/com/skocur/imagecipher/encrypters/RSAEncryption.java) that will work with all RSA public key formats.

It would be good if this code could use LowLevelBitEncryption. Something like presented below:
```java           
Encrypter encrypter = new LowLevelBitEncryption(fileName);
encrypter.encrypt(new String(encrypted, StandardCharsets.UTF_8));
```
where `encrypted` is variable that holds encrypted (via RSA) data.

**Comment by LQ95** [comment]
So you need someone to use your LowLevelBitEncryption class to make an RSA encryption algorhythm?

**Comment by SKocur** [comment]
Indeed, because LowLevelBitEncryption is tool used to store data in image.

**Comment by LQ95** [comment]
Alright. i'm a little busy with uni exams right now(computer science major lol) but I'd be interested in trying. I'll check back on this issue.

**Comment by SKocur** [comment]
No problem, so this is your issue @LQ95 . Good luck with exams! ;)

**Comment by LQ95** [comment]
alright. I'm still not entirely free,but I'd like to ask you a few questions about this.where can I message you? I would like to at least start working and I'm reading the documentation,right now

**Comment by SKocur** [comment]
You can send me direct message via Slack after you join Spack workspace. Invitation [link](https://join.slack.com/t/gitdevstudents/shared_invite/enQtMzE2ODU4Mjk2NDUzLTYyNDBjZTBlNmU3NGExMmU1ODVkZTc2MDQzOTQzNGFkODA5ZTZkZTllMjgyY2M2MjJlMmVjNDhiNzA1M2EwN2Y)
