### ISSUE TITLE
Add Button that will save image

### ISSUE THREAD

**Issue by SKocur** [SKocur/Image-Cipher#3]
User can process image with few options available to choose from GUI created in [FXML file](https://github.com/SKocur/Image-Cipher/blob/master/src/java/com/skocur/imagecipher/views/ImageProcessingWindow.fxml).

Add `Button` (in specified FXML file) that will be responsible for saving processed image to file. After it, implement feature that will enable user to do so. Here is "TODO" comment that will help: [code](https://github.com/SKocur/Image-Cipher/blob/master/src/java/com/skocur/imagecipher/controllers/ImageProcessingController.java#L71).

It would be nice to attach (in comment under this issue) screenshot that shows modified GUI.

**Comment by smohtadi** [comment]
Hi! I'm a first-timer and can work on this if its not taken.

**Comment by SKocur** [comment]
Hello @smohtadi this issue is not taken. You can take this one. If you have any questions do not hesitate to comment. :)

**Comment by smohtadi** [comment]
Great! I'll work on it and get back to you shortly. I have a question about the button's functionality. Would you like it to overwrite the original file, or save a a new file with a new name (e.g., processed_image.jpg>?

**Comment by SKocur** [comment]
I think saving it as a file with another name (like fileName_processed) will be perfect for now. In future we can implement feature that will make user choosing his own fileName, but for it I will create separate issue.
